
default: &default
  host: localhost
  adapter: postgresql
  pool: 5
  timeout: 5000
  

development:
  <<: *default
  database: hway_dev_db
  username: Andrew
  password: pirate

test:
  <<: *default

production:
  <<: *default
  database: d86hvh7l3klm2u
  username: fybivaazsdkwvo
  password: I49CNkea3UvhvUYGWDd719RB5i
