
default: &default
  host: localhost
  adapter: postgresql
  pool: 5
  timeout: 5000
  

development:
  <<: *default
  database: hway_dev_db
  username: Andrew
  password: pirate

test:
  <<: *default

production:
  <<: *default
